### ISSUE TITLE
Change the API to not require a singleton design

### ISSUE THREAD

**Issue by robyoder** [agilebits/t-i18n#3]
I feel that the singleton design is going to be a bit restrictive. Components should be able to specify on the spot the desired language. Using a curried function would be a great way to support both designs. Those who want a singleton can simply re-export the value `T("es")` or whatever. And if we want more flexibility, we can do `T("es", "My string")` or `T("es")("My string")` if auto-currying is not desired.

**Comment by mitchchn** [comment]
The singleton is already optional.

```ts
import { makeT } from "t-i18n";

const T = makeT();
const Q = makeT();

T.setup({locale: "es"});

Q.setup({locale: "de"});

console.log(T.locale);  // es
console.log(Q.locale); // de
```

**Comment by robyoder** [comment]
I see. The design still requires a saved state approach rather than ad hoc. For example there's no way to make T and set it up at the same time.

```js
const Component = (T, str) => $.div({}, T(str));

// I can't do this
Component(makeT().setup({ locale, messages }))

// Or this
Component(makeT({ locale, messages }))
```

But this probably is not the highest priority. I will probably set things up so that `T` is saved on the Context. That should give me enough flexibility (different sessions with different language settings) for now.

**Comment by mitchchn** [comment]
I get the value of having a fluent API or using currying to manage state, but keep in mind that this library needs to be statically analyzeable by the string extractor. That places unique constraints on the API.

For example, the string extractor used to parse calls to `T.setup()` so it could use the same ID generation function as the code. I ended up removing that feature because it was a bit too complex, but it would have been even harder to support with a fluent API.

By the way, `T("message")` only works with string literals for the same reason. For a dynamic value, you need to use `T.lookup` with an id:

```
const Component = (T, strId) => $.div({}, T.lookup(strId));
```

**Comment by robyoder** [comment]
Good points. Since `makeT` will solve my problems for now, I'll close this. If we run into further trouble in the future we can reconsider. Thanks!
